name: Build

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions: {}

jobs:
  build:
    name: Build (container)
    runs-on: ubuntu-latest
    permissions:
      artifact-metadata: write
      attestations: write
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Install Podman and jq
        run: |
          sudo apt-get update
          sudo apt-get -y install podman jq

      - name: Log into Container Registry with Podman
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Log into Container Registry with Docker
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          podman build --file ./Containerfile --squash --tag ${IMAGE}

      - name: Push container image
        id: push-container
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          podman push ${IMAGE} --digestfile=digest.txt
          echo digest=`cat digest.txt`
          echo digest=`cat digest.txt` >> $GITHUB_OUTPUT

      - name: Build SBOM
        run: |
          # actions/attest enforces presence of a "serialNumber" field in CycloneDX SBOMs.
          UUID="urn:uuid:$(uuidgen | tr '[:upper:]' '[:lower:]')"
          mkdir sbom-out
          jq -c  --arg uuid ${UUID} '. + {serialNumber: $uuid}' <sbom.cdx.json >sbom-out/sbom.cdx.json
          cat sbom-out/sbom.cdx.json

      - name: Validate SBOM
        run: |
          podman run --volume $(pwd)/sbom-out:/sbom:ro cyclonedx/cyclonedx-cli \
              validate --input-file /sbom/sbom.cdx.json --fail-on-errors

      - name: Attest SBOM
        uses: actions/attest@v4
        with:
          sbom-path: sbom-out/sbom.cdx.json
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push-container.outputs.digest }}

      - name: Attest build provenance
        uses: actions/attest@v4
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push-container.outputs.digest }}
          push-to-registry: true
